sudo: required
services:
  - docker

before_install:
  - docker build -t brtan/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run brtan/react-test npm test -- --coverage

after_success:
  - docker build -t brtan/multi-client ./client
  - docker build -t brtan/multi-nginx ./nginx
  - docker build -t brtan/multi-server ./server
  - docker build -t brtan/multi-worker ./worker
  #Login to Docker cli
  - echo "$PWD" | docker login -u "$ID" --password-stdin
  #Push images  to dockerhub
  - docker push brtan/multi-client
  - docker push brtan/multi-nginx
  - docker push brtan/multi-server
  - docker push brtan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-972318394795"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"